import {
  CompanySettings,
  VatRate,
  PaymentMethod,
  ProductCategory,
  Product,
  Customer,
  Quote,
  Invoice,
  Payment,
  CreditNote,
  AuditLog,
} from '@/types/database';

export const INITIAL_COMPANY_SETTINGS: CompanySettings = {
  id: 'org-sett-001',
  organization_id: 'org-default-001',
  legal_company_name: 'Al Thuraya Cloud Technologies LLC',
  trading_name: 'Al Thuraya Tech',
  trn: '100284759600003',
  tax_registration_date: '2018-01-01',
  address_line_1: 'Office 1402, Al Shatha Tower',
  address_line_2: 'Dubai Internet City',
  city: 'Dubai',
  emirate: 'DUBAI',
  country: 'United Arab Emirates',
  po_box: '500123',
  email: 'billing@althurayatech.ae',
  phone: '+971 4 429 8800',
  mobile: '+971 50 123 4567',
  website: 'https://althurayatech.ae',
  default_currency: 'AED',
  default_vat_rate: 5,
  invoice_prefix: 'INV',
  quote_prefix: 'QUO',
  credit_note_prefix: 'CN',
  payment_prefix: 'PAY',
  default_payment_terms_days: 30,
  bank_name: 'First Abu Dhabi Bank (FAB)',
  bank_account_name: 'Al Thuraya Cloud Technologies LLC',
  bank_account_number: '109283746501',
  bank_iban: 'AE070330000109283746501',
  bank_swift_bic: 'FABAEADXXX',
  bank_branch: 'Dubai Internet City Branch',
  invoice_footer_notes: 'Thank you for choosing Al Thuraya Tech. Registered under UAE VAT Law.',
  terms_and_conditions: 'Payment is due within 30 days of invoice date. Cheques payable to "Al Thuraya Cloud Technologies LLC".',
  created_at: new Date('2026-01-01').toISOString(),
  updated_at: new Date('2026-01-01').toISOString(),
};

export const INITIAL_VAT_RATES: VatRate[] = [
  {
    id: 'vat-001',
    organization_id: 'org-default-001',
    code: 'STANDARD_5',
    name: 'Standard Rated (5%)',
    rate_percentage: 5.0,
    treatment: 'STANDARD_RATED',
    is_active: true,
    is_default: true,
  },
  {
    id: 'vat-002',
    organization_id: 'org-default-001',
    code: 'ZERO_0',
    name: 'Zero Rated (0%)',
    rate_percentage: 0.0,
    treatment: 'ZERO_RATED',
    is_active: true,
    is_default: false,
  },
  {
    id: 'vat-003',
    organization_id: 'org-default-001',
    code: 'EXEMPT',
    name: 'Exempt',
    rate_percentage: 0.0,
    treatment: 'EXEMPT',
    is_active: true,
    is_default: false,
  },
  {
    id: 'vat-004',
    organization_id: 'org-default-001',
    code: 'OUT_OF_SCOPE',
    name: 'Out of Scope',
    rate_percentage: 0.0,
    treatment: 'OUT_OF_SCOPE',
    is_active: true,
    is_default: false,
  },
];

export const INITIAL_PAYMENT_METHODS: PaymentMethod[] = [
  { id: 'pm-001', organization_id: 'org-default-001', name: 'Bank Transfer (Wire)', code: 'BANK_TRANSFER', is_active: true },
  { id: 'pm-002', organization_id: 'org-default-001', name: 'Company Cheque', code: 'CHEQUE', is_active: true },
  { id: 'pm-003', organization_id: 'org-default-001', name: 'Corporate Credit Card', code: 'CREDIT_CARD', is_active: true },
  { id: 'pm-004', organization_id: 'org-default-001', name: 'Cash', code: 'CASH', is_active: true },
];

export const INITIAL_CATEGORIES: ProductCategory[] = [
  { id: 'cat-001', organization_id: 'org-default-001', name: 'Cloud Infrastructure & Hosting', description: 'UAE sovereign cloud and VPS solutions' },
  { id: 'cat-002', organization_id: 'org-default-001', name: 'Software & Architecture Consulting', description: 'Enterprise engineering and development' },
  { id: 'cat-003', organization_id: 'org-default-001', name: 'Cybersecurity & Compliance', description: 'Penetration testing and security auditing' },
  { id: 'cat-004', organization_id: 'org-default-001', name: 'Managed IT Support', description: 'Retainers and 24/7 SLA coverage' },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    organization_id: 'org-default-001',
    category_id: 'cat-002',
    category_name: 'Software & Architecture Consulting',
    name: 'Enterprise Cloud Architecture Consulting',
    sku: 'SRV-ARCH-01',
    description: 'Senior architectural guidance, microservice planning, and cloud governance.',
    unit: 'Hour',
    cost_price: 250.0,
    selling_price: 500.0,
    vat_rate_id: 'vat-001',
    vat_rate_percentage: 5.0,
    vat_treatment: 'STANDARD_RATED',
    is_active: true,
    created_at: new Date('2026-01-05').toISOString(),
    updated_at: new Date('2026-01-05').toISOString(),
  },
  {
    id: 'prod-002',
    organization_id: 'org-default-001',
    category_id: 'cat-001',
    category_name: 'Cloud Infrastructure & Hosting',
    name: 'UAE Dedicated Managed VPS (8 vCPU / 32GB)',
    sku: 'INF-VPS-08',
    description: 'High performance NVMe cloud instance hosted in Dubai Tier-IV data center.',
    unit: 'Month',
    cost_price: 450.0,
    selling_price: 950.0,
    vat_rate_id: 'vat-001',
    vat_rate_percentage: 5.0,
    vat_treatment: 'STANDARD_RATED',
    is_active: true,
    created_at: new Date('2026-01-05').toISOString(),
    updated_at: new Date('2026-01-05').toISOString(),
  },
  {
    id: 'prod-003',
    organization_id: 'org-default-001',
    category_id: 'cat-003',
    category_name: 'Cybersecurity & Compliance',
    name: 'UAE NESA Security Compliance Audit',
    sku: 'SEC-NESA-01',
    description: 'Full assessment and gap analysis for UAE Information Assurance standards.',
    unit: 'Service',
    cost_price: 3500.0,
    selling_price: 7500.0,
    vat_rate_id: 'vat-001',
    vat_rate_percentage: 5.0,
    vat_treatment: 'STANDARD_RATED',
    is_active: true,
    created_at: new Date('2026-01-05').toISOString(),
    updated_at: new Date('2026-01-05').toISOString(),
  },
  {
    id: 'prod-004',
    organization_id: 'org-default-001',
    category_id: 'cat-001',
    category_name: 'Cloud Infrastructure & Hosting',
    name: 'Cross-Border Data Sync & Offshore Relay',
    sku: 'INF-RELAY-02',
    description: 'Export service for international nodes outside GCC.',
    unit: 'Month',
    cost_price: 300.0,
    selling_price: 650.0,
    vat_rate_id: 'vat-002',
    vat_rate_percentage: 0.0,
    vat_treatment: 'ZERO_RATED',
    is_active: true,
    created_at: new Date('2026-01-05').toISOString(),
    updated_at: new Date('2026-01-05').toISOString(),
  },
  {
    id: 'prod-005',
    organization_id: 'org-default-001',
    category_id: 'cat-004',
    category_name: 'Managed IT Support',
    name: 'Monthly 24/7 Priority Support Retainer (20h)',
    sku: 'SUP-RET-20',
    description: 'Guaranteed 15-minute SLA response for production services.',
    unit: 'Month',
    cost_price: 1800.0,
    selling_price: 3400.0,
    vat_rate_id: 'vat-001',
    vat_rate_percentage: 5.0,
    vat_treatment: 'STANDARD_RATED',
    is_active: true,
    created_at: new Date('2026-01-05').toISOString(),
    updated_at: new Date('2026-01-05').toISOString(),
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-001',
    organization_id: 'org-default-001',
    customer_type: 'COMPANY',
    relation_type: 'CUSTOMER',
    company_name: 'Dubai Logistics Global FZ-LLC',
    contact_person: 'Farhan Siddiqui',
    email: 'accounts@dubailogistics.ae',
    phone: '+971 4 883 1200',
    mobile: '+971 52 987 6543',
    trn: '100384756200003',
    billing_address_line_1: 'Building B, Logistics City',
    billing_address_line_2: 'Dubai South',
    billing_city: 'Dubai',
    billing_emirate: 'DUBAI',
    billing_country: 'United Arab Emirates',
    billing_po_box: '98402',
    payment_terms_days: 30,
    currency: 'AED',
    notes: 'Key client for logistics warehouse cloud management.',
    is_active: true,
    created_at: new Date('2026-01-10').toISOString(),
    updated_at: new Date('2026-01-10').toISOString(),
    contacts: [
      { id: 'cnt-01', customer_id: 'cust-001', name: 'Farhan Siddiqui', designation: 'Finance Director', email: 'accounts@dubailogistics.ae', is_primary: true },
      { id: 'cnt-02', customer_id: 'cust-001', name: 'Nadia El-Sayed', designation: 'Operations Manager', email: 'nadia@dubailogistics.ae', is_primary: false },
    ],
  },
  {
    id: 'cust-002',
    organization_id: 'org-default-001',
    customer_type: 'COMPANY',
    relation_type: 'CUSTOMER',
    company_name: 'Abu Dhabi Clean Energy Solutions PJSC',
    contact_person: 'Dr. Sultan Al Mazrouei',
    email: 'billing@adcleanenergy.ae',
    phone: '+971 2 690 4000',
    mobile: '+971 50 445 6789',
    trn: '100918273400003',
    billing_address_line_1: 'Level 21, Al Khatem Tower',
    billing_address_line_2: 'ADGM Square, Al Maryah Island',
    billing_city: 'Abu Dhabi',
    billing_emirate: 'ABU_DHABI',
    billing_country: 'United Arab Emirates',
    billing_po_box: '44100',
    payment_terms_days: 45,
    currency: 'AED',
    notes: 'Government-aligned energy research partner.',
    is_active: true,
    created_at: new Date('2026-01-12').toISOString(),
    updated_at: new Date('2026-01-12').toISOString(),
  },
  {
    id: 'cust-003',
    organization_id: 'org-default-001',
    customer_type: 'COMPANY',
    relation_type: 'CUSTOMER',
    company_name: 'Gulf Retail Partners Ltd',
    contact_person: 'Hassan Bin Saeed',
    email: 'finance@gulfretail.ae',
    phone: '+971 6 528 9000',
    mobile: '+971 55 678 1234',
    trn: '100746352900003',
    billing_address_line_1: 'Warehouse 12, Industrial Area 4',
    billing_city: 'Sharjah',
    billing_emirate: 'SHARJAH',
    billing_country: 'United Arab Emirates',
    payment_terms_days: 15,
    currency: 'AED',
    notes: 'Retail chain operating 18 outlets across Emirates.',
    is_active: true,
    created_at: new Date('2026-01-15').toISOString(),
    updated_at: new Date('2026-01-15').toISOString(),
  },
  {
    id: 'cust-004',
    organization_id: 'org-default-001',
    customer_type: 'COMPANY',
    relation_type: 'PROSPECT',
    company_name: 'Sheikh Rashid Real Estate Investments',
    contact_person: 'Rashid Al Nuaimi',
    email: 'info@rashidinvest.ae',
    phone: '+971 4 330 9900',
    billing_address_line_1: 'Boulevard Plaza Tower 1',
    billing_city: 'Dubai',
    billing_emirate: 'DUBAI',
    billing_country: 'United Arab Emirates',
    payment_terms_days: 30,
    currency: 'AED',
    notes: 'Negotiating annual IT architecture contract for new residential portal.',
    is_active: true,
    created_at: new Date('2026-02-01').toISOString(),
    updated_at: new Date('2026-02-01').toISOString(),
  },
  {
    id: 'cust-005',
    organization_id: 'org-default-001',
    customer_type: 'INDIVIDUAL',
    relation_type: 'PROSPECT',
    contact_person: 'Tariq Al Mansoori',
    email: 'tariq.mansoori@gmail.com',
    mobile: '+971 50 998 7766',
    billing_address_line_1: 'Villa 14, Street 18',
    billing_city: 'Dubai',
    billing_emirate: 'DUBAI',
    billing_country: 'United Arab Emirates',
    payment_terms_days: 0,
    currency: 'AED',
    notes: 'Private technology consulting inquiries.',
    is_active: true,
    created_at: new Date('2026-02-10').toISOString(),
    updated_at: new Date('2026-02-10').toISOString(),
  },
];

export const INITIAL_QUOTES: Quote[] = [
  {
    id: 'quo-001',
    organization_id: 'org-default-001',
    customer_id: 'cust-001',
    customer_name: 'Dubai Logistics Global FZ-LLC',
    customer_email: 'accounts@dubailogistics.ae',
    customer_trn: '100384756200003',
    quote_number: 'QUO-2026-0001',
    quote_date: '2026-01-15',
    expiry_date: '2026-02-15',
    status: 'CONVERTED',
    currency: 'AED',
    exchange_rate: 1.0,
    subtotal_net: 10000.0,
    discount_value: 0,
    discount_amount: 0,
    vat_total: 500.0,
    grand_total: 10500.0,
    converted_invoice_id: 'inv-001',
    notes: 'Annual setup and cloud architecture initialization.',
    items: [
      {
        id: 'qi-001',
        product_id: 'prod-001',
        item_order: 1,
        description: 'Enterprise Cloud Architecture Consulting',
        quantity: 20,
        unit_price: 500.0,
        unit: 'Hour',
        discount_value: 0,
        discount_amount: 0,
        subtotal_net: 10000.0,
        vat_rate_id: 'vat-001',
        vat_rate_percentage: 5.0,
        vat_amount: 500.0,
        total_gross: 10500.0,
      },
    ],
    created_at: new Date('2026-01-15').toISOString(),
    updated_at: new Date('2026-01-20').toISOString(),
  },
  {
    id: 'quo-002',
    organization_id: 'org-default-001',
    customer_id: 'cust-004',
    customer_name: 'Sheikh Rashid Real Estate Investments',
    customer_email: 'info@rashidinvest.ae',
    quote_number: 'QUO-2026-0002',
    quote_date: '2026-02-05',
    expiry_date: '2026-03-20',
    status: 'SENT',
    currency: 'AED',
    exchange_rate: 1.0,
    subtotal_net: 14200.0,
    discount_type: 'PERCENTAGE',
    discount_value: 5,
    discount_amount: 710.0,
    vat_total: 674.5,
    grand_total: 14164.5,
    notes: 'Proposal for NESA compliance security assessment and 2 months dedicated cloud VPS.',
    items: [
      {
        id: 'qi-002',
        product_id: 'prod-003',
        item_order: 1,
        description: 'UAE NESA Security Compliance Audit',
        quantity: 1,
        unit_price: 7500.0,
        unit: 'Service',
        discount_value: 0,
        discount_amount: 0,
        subtotal_net: 7500.0,
        vat_rate_id: 'vat-001',
        vat_rate_percentage: 5.0,
        vat_amount: 375.0,
        total_gross: 7875.0,
      },
      {
        id: 'qi-003',
        product_id: 'prod-005',
        item_order: 2,
        description: 'Monthly 24/7 Priority Support Retainer (20h)',
        quantity: 2,
        unit_price: 3400.0,
        unit: 'Month',
        discount_value: 100,
        discount_type: 'FIXED_AMOUNT',
        discount_amount: 100.0,
        subtotal_net: 6700.0,
        vat_rate_id: 'vat-001',
        vat_rate_percentage: 5.0,
        vat_amount: 335.0,
        total_gross: 7035.0,
      },
    ],
    created_at: new Date('2026-02-05').toISOString(),
    updated_at: new Date('2026-02-06').toISOString(),
  },
  {
    id: 'quo-003',
    organization_id: 'org-default-001',
    customer_id: 'cust-003',
    customer_name: 'Gulf Retail Partners Ltd',
    customer_email: 'finance@gulfretail.ae',
    customer_trn: '100746352900003',
    quote_number: 'QUO-2026-0003',
    quote_date: '2026-02-20',
    expiry_date: '2026-03-25',
    status: 'DRAFT',
    currency: 'AED',
    exchange_rate: 1.0,
    subtotal_net: 4750.0,
    discount_value: 0,
    discount_amount: 0,
    vat_total: 237.5,
    grand_total: 4987.5,
    notes: 'Draft quote for 5 VPS hostings across Sharjah distribution centers.',
    items: [
      {
        id: 'qi-004',
        product_id: 'prod-002',
        item_order: 1,
        description: 'UAE Dedicated Managed VPS (8 vCPU / 32GB)',
        quantity: 5,
        unit_price: 950.0,
        unit: 'Month',
        discount_value: 0,
        discount_amount: 0,
        subtotal_net: 4750.0,
        vat_rate_id: 'vat-001',
        vat_rate_percentage: 5.0,
        vat_amount: 237.5,
        total_gross: 4987.5,
      },
    ],
    created_at: new Date('2026-02-20').toISOString(),
    updated_at: new Date('2026-02-20').toISOString(),
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-001',
    organization_id: 'org-default-001',
    customer_id: 'cust-001',
    originating_quote_id: 'quo-001',
    originating_quote_number: 'QUO-2026-0001',
    invoice_number: 'INV-2026-0001',
    invoice_date: '2026-01-20',
    supply_date: '2026-01-20',
    due_date: '2026-02-19',
    status: 'PAID',
    currency: 'AED',
    exchange_rate: 1.0,
    subtotal_net: 10000.0,
    discount_value: 0,
    discount_amount: 0,
    vat_total: 500.0,
    grand_total: 10500.0,
    amount_paid: 10500.0,
    balance_due: 0.0,
    customer_snapshot: {
      company_name: 'Dubai Logistics Global FZ-LLC',
      contact_person: 'Farhan Siddiqui',
      email: 'accounts@dubailogistics.ae',
      trn: '100384756200003',
      billing_address_line_1: 'Building B, Logistics City, Dubai South',
      billing_city: 'Dubai',
      billing_emirate: 'DUBAI',
    },
    company_snapshot: {
      legal_company_name: 'Al Thuraya Cloud Technologies LLC',
      trn: '100284759600003',
      address_line_1: 'Office 1402, Al Shatha Tower, Dubai Internet City',
      city: 'Dubai',
      emirate: 'DUBAI',
      email: 'billing@althurayatech.ae',
    },
    bank_details_snapshot: {
      bank_name: 'First Abu Dhabi Bank (FAB)',
      account_name: 'Al Thuraya Cloud Technologies LLC',
      account_number: '109283746501',
      iban: 'AE07033109283746501',
      swift_bic: 'FABAEADXXX',
      branch: 'Dubai Internet City Branch',
    },
    notes: 'Converted from Quotation QUO-2026-0001.',
    terms: 'Full payment received.',
    e_invoice_status: 'ACCEPTED',
    e_invoice_uuid: 'uae-einvoice-7f28ba90-20260120',
    e_invoice_hash: 'sha256:d48e89f8123abc4902348fa918237',
    e_invoice_qr_code: 'https://tax.gov.ae/einvoice/verify?doc=INV-2026-0001&trn=100284759600003&total=10500.00',
    e_invoice_submitted_at: '2026-01-20T10:00:00Z',
    items: [
      {
        id: 'ii-001',
        product_id: 'prod-001',
        item_order: 1,
        description: 'Enterprise Cloud Architecture Consulting',
        quantity: 20,
        unit_price: 500.0,
        unit: 'Hour',
        discount_value: 0,
        discount_amount: 0,
        subtotal_net: 10000.0,
        vat_rate_id: 'vat-001',
        vat_rate_percentage: 5.0,
        vat_amount: 500.0,
        total_gross: 10500.0,
      },
    ],
    created_at: new Date('2026-01-20').toISOString(),
    updated_at: new Date('2026-02-05').toISOString(),
  },
  {
    id: 'inv-002',
    organization_id: 'org-default-001',
    customer_id: 'cust-002',
    invoice_number: 'INV-2026-0002',
    invoice_date: '2026-02-01',
    supply_date: '2026-02-01',
    due_date: '2026-03-18',
    status: 'PARTIALLY_PAID',
    currency: 'AED',
    exchange_rate: 1.0,
    subtotal_net: 10000.0,
    discount_value: 0,
    discount_amount: 0,
    vat_total: 500.0,
    grand_total: 10500.0,
    amount_paid: 5000.0,
    balance_due: 5500.0,
    customer_snapshot: {
      company_name: 'Abu Dhabi Clean Energy Solutions PJSC',
      contact_person: 'Dr. Sultan Al Mazrouei',
      email: 'billing@adcleanenergy.ae',
      trn: '100918273400003',
      billing_address_line_1: 'Level 21, Al Khatem Tower, ADGM Square',
      billing_city: 'Abu Dhabi',
      billing_emirate: 'ABU_DHABI',
    },
    company_snapshot: {
      legal_company_name: 'Al Thuraya Cloud Technologies LLC',
      trn: '100284759600003',
      address_line_1: 'Office 1402, Al Shatha Tower, Dubai Internet City',
      city: 'Dubai',
      emirate: 'DUBAI',
    },
    bank_details_snapshot: {
      bank_name: 'First Abu Dhabi Bank (FAB)',
      account_name: 'Al Thuraya Cloud Technologies LLC',
      account_number: '109283746501',
      iban: 'AE07033109283746501',
      swift_bic: 'FABAEADXXX',
    },
    notes: 'Q1 Security Audit and advisory retainer.',
    e_invoice_status: 'ACCEPTED',
    e_invoice_uuid: 'uae-einvoice-819aef02-20260201',
    e_invoice_hash: 'sha256:88fa29810abf10398',
    items: [
      {
        id: 'ii-002',
        product_id: 'prod-003',
        item_order: 1,
        description: 'UAE NESA Security Compliance Audit',
        quantity: 1,
        unit_price: 7500.0,
        unit: 'Service',
        discount_value: 0,
        discount_amount: 0,
        subtotal_net: 7500.0,
        vat_rate_id: 'vat-001',
        vat_rate_percentage: 5.0,
        vat_amount: 375.0,
        total_gross: 7875.0,
      },
      {
        id: 'ii-003',
        product_id: 'prod-001',
        item_order: 2,
        description: 'Enterprise Cloud Architecture Consulting',
        quantity: 5,
        unit_price: 500.0,
        unit: 'Hour',
        discount_value: 0,
        discount_amount: 0,
        subtotal_net: 2500.0,
        vat_rate_id: 'vat-001',
        vat_rate_percentage: 5.0,
        vat_amount: 125.0,
        total_gross: 2625.0,
      },
    ],
    created_at: new Date('2026-02-01').toISOString(),
    updated_at: new Date('2026-02-15').toISOString(),
  },
  {
    id: 'inv-003',
    organization_id: 'org-default-001',
    customer_id: 'cust-003',
    invoice_number: 'INV-2026-0003',
    invoice_date: '2026-02-15',
    supply_date: '2026-02-15',
    due_date: '2026-03-02',
    status: 'ISSUED',
    currency: 'AED',
    exchange_rate: 1.0,
    subtotal_net: 3800.0,
    discount_value: 0,
    discount_amount: 0,
    vat_total: 190.0,
    grand_total: 3990.0,
    amount_paid: 0.0,
    balance_due: 3990.0,
    customer_snapshot: {
      company_name: 'Gulf Retail Partners Ltd',
      contact_person: 'Hassan Bin Saeed',
      email: 'finance@gulfretail.ae',
      trn: '100746352900003',
      billing_address_line_1: 'Warehouse 12, Industrial Area 4, Sharjah',
      billing_city: 'Sharjah',
      billing_emirate: 'SHARJAH',
    },
    company_snapshot: {
      legal_company_name: 'Al Thuraya Cloud Technologies LLC',
      trn: '100284759600003',
      address_line_1: 'Office 1402, Al Shatha Tower, Dubai Internet City',
      city: 'Dubai',
      emirate: 'DUBAI',
    },
    e_invoice_status: 'ACCEPTED',
    e_invoice_uuid: 'uae-einvoice-c9349811-20260215',
    items: [
      {
        id: 'ii-004',
        product_id: 'prod-002',
        item_order: 1,
        description: 'UAE Dedicated Managed VPS (8 vCPU / 32GB)',
        quantity: 4,
        unit_price: 950.0,
        unit: 'Month',
        discount_value: 0,
        discount_amount: 0,
        subtotal_net: 3800.0,
        vat_rate_id: 'vat-001',
        vat_rate_percentage: 5.0,
        vat_amount: 190.0,
        total_gross: 3990.0,
      },
    ],
    created_at: new Date('2026-02-15').toISOString(),
    updated_at: new Date('2026-02-15').toISOString(),
  },
  {
    id: 'inv-004',
    organization_id: 'org-default-001',
    customer_id: 'cust-003',
    invoice_number: 'INV-2026-0004',
    invoice_date: '2026-01-05',
    supply_date: '2026-01-05',
    due_date: '2026-01-20',
    status: 'OVERDUE',
    currency: 'AED',
    exchange_rate: 1.0,
    subtotal_net: 3400.0,
    discount_value: 0,
    discount_amount: 0,
    vat_total: 170.0,
    grand_total: 3570.0,
    amount_paid: 0.0,
    balance_due: 3570.0,
    customer_snapshot: {
      company_name: 'Gulf Retail Partners Ltd',
      contact_person: 'Hassan Bin Saeed',
      email: 'finance@gulfretail.ae',
      trn: '100746352900003',
    },
    company_snapshot: {
      legal_company_name: 'Al Thuraya Cloud Technologies LLC',
      trn: '100284759600003',
    },
    notes: 'Past due notice sent.',
    e_invoice_status: 'ACCEPTED',
    items: [
      {
        id: 'ii-005',
        product_id: 'prod-005',
        item_order: 1,
        description: 'Monthly 24/7 Priority Support Retainer (20h)',
        quantity: 1,
        unit_price: 3400.0,
        unit: 'Month',
        discount_value: 0,
        discount_amount: 0,
        subtotal_net: 3400.0,
        vat_rate_id: 'vat-001',
        vat_rate_percentage: 5.0,
        vat_amount: 170.0,
        total_gross: 3570.0,
      },
    ],
    created_at: new Date('2026-01-05').toISOString(),
    updated_at: new Date('2026-01-21').toISOString(),
  },
  {
    id: 'inv-005',
    organization_id: 'org-default-001',
    customer_id: 'cust-001',
    invoice_number: 'INV-2026-0005',
    invoice_date: '2026-02-10',
    supply_date: '2026-02-10',
    due_date: '2026-03-12',
    status: 'CANCELLED',
    currency: 'AED',
    exchange_rate: 1.0,
    subtotal_net: 1300.0,
    discount_value: 0,
    discount_amount: 0,
    vat_total: 0.0,
    grand_total: 1300.0,
    amount_paid: 0.0,
    balance_due: 0.0,
    customer_snapshot: {
      company_name: 'Dubai Logistics Global FZ-LLC',
      trn: '100384756200003',
    },
    company_snapshot: {
      legal_company_name: 'Al Thuraya Cloud Technologies LLC',
      trn: '100284759600003',
    },
    cancelled_at: '2026-02-11T09:30:00Z',
    cancellation_reason: 'Entered under incorrect service SKU before customer dispatch. Replaced by updated agreement.',
    e_invoice_status: 'CANCELLED',
    items: [
      {
        id: 'ii-006',
        product_id: 'prod-004',
        item_order: 1,
        description: 'Cross-Border Data Sync & Offshore Relay',
        quantity: 2,
        unit_price: 650.0,
        unit: 'Month',
        discount_value: 0,
        discount_amount: 0,
        subtotal_net: 1300.0,
        vat_rate_id: 'vat-002',
        vat_rate_percentage: 0.0,
        vat_amount: 0.0,
        total_gross: 1300.0,
      },
    ],
    created_at: new Date('2026-02-10').toISOString(),
    updated_at: new Date('2026-02-11').toISOString(),
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay-001',
    organization_id: 'org-default-001',
    invoice_id: 'inv-001',
    invoice_number: 'INV-2026-0001',
    customer_id: 'cust-001',
    customer_name: 'Dubai Logistics Global FZ-LLC',
    payment_number: 'PAY-2026-0001',
    payment_date: '2026-01-28',
    payment_method_id: 'pm-001',
    payment_method_name: 'Bank Transfer (Wire)',
    amount: 5000.0,
    currency: 'AED',
    exchange_rate: 1.0,
    reference_number: 'FT-FAB-99281726',
    notes: 'Installment 1 of 2 via FAB Wire.',
    status: 'RECORDED',
    created_at: new Date('2026-01-28').toISOString(),
    updated_at: new Date('2026-01-28').toISOString(),
  },
  {
    id: 'pay-002',
    organization_id: 'org-default-001',
    invoice_id: 'inv-001',
    invoice_number: 'INV-2026-0001',
    customer_id: 'cust-001',
    customer_name: 'Dubai Logistics Global FZ-LLC',
    payment_number: 'PAY-2026-0002',
    payment_date: '2026-02-05',
    payment_method_id: 'pm-001',
    payment_method_name: 'Bank Transfer (Wire)',
    amount: 5500.0,
    currency: 'AED',
    exchange_rate: 1.0,
    reference_number: 'FT-FAB-99384711',
    notes: 'Final settlement installment. Invoice fully cleared.',
    status: 'RECORDED',
    created_at: new Date('2026-02-05').toISOString(),
    updated_at: new Date('2026-02-05').toISOString(),
  },
  {
    id: 'pay-003',
    organization_id: 'org-default-001',
    invoice_id: 'inv-002',
    invoice_number: 'INV-2026-0002',
    customer_id: 'cust-002',
    customer_name: 'Abu Dhabi Clean Energy Solutions PJSC',
    payment_number: 'PAY-2026-0003',
    payment_date: '2026-02-15',
    payment_method_id: 'pm-002',
    payment_method_name: 'Company Cheque',
    amount: 5000.0,
    currency: 'AED',
    exchange_rate: 1.0,
    reference_number: 'CHQ-ADCB-449182',
    notes: 'Advance deposit cheque cleared.',
    status: 'RECORDED',
    created_at: new Date('2026-02-15').toISOString(),
    updated_at: new Date('2026-02-15').toISOString(),
  },
];

export const INITIAL_CREDIT_NOTES: CreditNote[] = [
  {
    id: 'cn-001',
    organization_id: 'org-default-001',
    invoice_id: 'inv-001',
    invoice_number: 'INV-2026-0001',
    customer_id: 'cust-001',
    customer_name: 'Dubai Logistics Global FZ-LLC',
    credit_note_number: 'CN-2026-0001',
    credit_note_date: '2026-02-08',
    status: 'APPLIED',
    reason: 'Price adjustment on 2 consulting hours following project retrospective.',
    currency: 'AED',
    subtotal_net: 1000.0,
    discount_amount: 0,
    vat_total: 50.0,
    grand_total: 1050.0,
    remaining_balance: 0.0,
    customer_snapshot: {
      company_name: 'Dubai Logistics Global FZ-LLC',
      trn: '100384756200003',
    },
    company_snapshot: {
      legal_company_name: 'Al Thuraya Cloud Technologies LLC',
      trn: '100284759600003',
    },
    e_invoice_status: 'ACCEPTED',
    e_invoice_uuid: 'uae-cn-88349281-20260208',
    items: [
      {
        id: 'cni-001',
        credit_note_id: 'cn-001',
        invoice_item_id: 'ii-001',
        product_id: 'prod-001',
        item_order: 1,
        description: 'Enterprise Cloud Architecture Consulting - Credit Adjustment',
        quantity: 2,
        unit_price: 500.0,
        unit: 'Hour',
        discount_amount: 0,
        subtotal_net: 1000.0,
        vat_rate_id: 'vat-001',
        vat_rate_percentage: 5.0,
        vat_amount: 50.0,
        total_gross: 1050.0,
      },
    ],
    allocations: [
      {
        id: 'cna-001',
        organization_id: 'org-default-001',
        credit_note_id: 'cn-001',
        invoice_id: 'inv-001',
        amount: 1050.0,
        allocation_type: 'CASH_REFUND',
        allocated_at: '2026-02-08T12:00:00Z',
      },
    ],
    created_at: new Date('2026-02-08').toISOString(),
    updated_at: new Date('2026-02-08').toISOString(),
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-001',
    organization_id: 'org-default-001',
    entity_type: 'INVOICE',
    entity_id: 'inv-001',
    action: 'ISSUED',
    performed_by_name: 'System Admin',
    created_at: new Date('2026-01-20T08:00:00Z').toISOString(),
    new_values: { invoice_number: 'INV-2026-0001', status: 'ISSUED', grand_total: 10500.0 },
  },
  {
    id: 'aud-002',
    organization_id: 'org-default-001',
    entity_type: 'PAYMENT',
    entity_id: 'pay-001',
    action: 'RECORDED',
    performed_by_name: 'Accountant',
    created_at: new Date('2026-01-28T11:20:00Z').toISOString(),
    new_values: { payment_number: 'PAY-2026-0001', amount: 5000.0, invoice_number: 'INV-2026-0001' },
  },
  {
    id: 'aud-003',
    organization_id: 'org-default-001',
    entity_type: 'PAYMENT',
    entity_id: 'pay-002',
    action: 'RECORDED',
    performed_by_name: 'Accountant',
    created_at: new Date('2026-02-05T14:15:00Z').toISOString(),
    new_values: { payment_number: 'PAY-2026-0002', amount: 5500.0, invoice_number: 'INV-2026-0001' },
  },
  {
    id: 'aud-004',
    organization_id: 'org-default-001',
    entity_type: 'INVOICE',
    entity_id: 'inv-005',
    action: 'CANCELLED',
    performed_by_name: 'Operations Lead',
    created_at: new Date('2026-02-11T09:30:00Z').toISOString(),
    old_values: { status: 'ISSUED' },
    new_values: { status: 'CANCELLED', reason: 'Entered under incorrect service SKU before customer dispatch.' },
  },
];
